spring:
  datasource:
    url: jdbc:mysql://demo.csfp9hcywqnb.ap-northeast-2.rds.amazonaws.com/demo?serverTimezone=UTC&characterEncoding=UTF-8
    username: fun2314
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

jwt:
  header: Authorization
  # news-whale-backend-with-springboot-for-login-authorization-and-authentication-jwt-security-key 를 BASE64로 인코딩한 값
  secret: bmV3cy13aGFsZS1iYWNrZW5kLXdpdGgtc3ByaW5nYm9vdC1mb3ItbG9naW4tYXV0aG9yaXphdGlvbi1hbmQtYXV0aGVudGljYXRpb24tand0LXNlY3VyaXR5LWtleQ==
  # 토큰 만료 시간
  token-validity-in-seconds: 86400

logging:
  level:
    org.hibernate.SQL: debug