INSERT INTO user (USER_ID, USERNAME, PASSWORD, NICKNAME, EMAIL, ACTIVATED, POLITICS_SCORE, ECONOMY_SCORE, SOCIETY_SCORE, CULTURE_SCORE, INTERNATIONAL_SCORE, LOCAL_SCORE, SPORTS_SCORE, IT_SCIENCE_SCORE)
VALUES (1, "admin", "$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi", "admin", "admin", 1, 0, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO authority (AUTHORITY_NAME) VALUES ('ROLE_USER');
INSERT INTO authority (AUTHORITY_NAME) VALUES ('ROLE_ADMIN');

INSERT INTO user_authority (USER_ID, AUTHORITY_NAME) VALUES (1, 'ROLE_ADMIN');

-- INSERT INTO user (USERNAME, PASSWORD, NICKNAME, EMAIL, ACTIVATED, POLITICS_SCORE, ECONOMY_SCORE, SOCIETY_SCORE, CULTURE_SCORE, INTERNATIONAL_SCORE, LOCAL_SCORE, SPORTS_SCORE, IT_SCIENCE_SCORE)
-- VALUES ("admin", "$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi", "admin", "admin", 1, 0, 0, 0, 0, 0, 0, 0, 0);